# Generated by Django 3.0.1 on 2020-04-15 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transact_date', models.DateField(default=datetime.date.today, verbose_name='Transaction Date')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transactDet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transactDet_desc', models.CharField(default='', max_length=250, verbose_name='Desc.')),
                ('rm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='RM')),
                ('usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='USD')),
                ('rmb', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='RMB')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='accounts.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bhante'), (2, 'Sayalay'), (3, 'Office Admin')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
